### ISSUE TITLE
Logs in /var/log/automydumper/ not automatically cleared

### ISSUE THREAD

**Issue by StoneNinja** [automydumper/automydumper#10]
Every time you take a backup, automydumper drops a file in /var/log/automydumper. But automydumper doesn't clear the oldest logfile.
I would be great when automydumper cleans up the backups, it also cleans up the log files.

**Comment by verwilst** [comment]
I'm going to switch to /var/log/automydumper.log and add a logrotate file to the package. Otherwise I feel I need to many logical paths to prune the correct log files.

**Comment by verwilst** [comment]
Logs are now stored inside the backup directory.
