### ISSUE TITLE
Cannot create a JSON value from a string with CHARACTER SET 'binary'.

### ISSUE THREAD

**Issue by Vandersteen** [automydumper/automydumper#12]
When restoring a backup from automydumper, I'm getting the following error for JSON fields

```
Cannot create a JSON value from a string with CHARACTER SET 'binary'.
```

Usage to 'reimport':

```
zcat * | mysql -u user -p database
```

**Comment by verwilst** [comment]
Since automydumper is just a wrapper around mydumper, this seems to be a Mydumper issue instead. Could you try pinpointing the exact table that is giving you this issue? Using a for loop instead of a wildcard for example. That way at least it's clear what statement is triggering the issue.

**Comment by verwilst** [comment]
A new mydumper version has been released in the meantime. Please upgrade to the latest mydumper package, and report a bug there if you're still having this issue. Thanks!
